# https://hub.docker.com/_/mysql?tab=description

version: '3.1'

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example # User is 'root'
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - 33060:33060
      - 3306:3306

volumes:
  data-volume:

# Exec into the container to set things up:
# mysql --password
#  mysql> create database db_example;   -- Create the new database
#  mysql> create user 'springuser'@'%' identified by 'ThePassword';  -- Creates the user
#  mysql> grant all on db_example.* to 'springuser'@'%';   -- Gives all the privileges to the new user on the newly created database